### ISSUE TITLE
dRICH: use true sensor thickness and add resin base

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#111]
**Is your feature request related to a problem? Please describe.**
The sensor should be made more realistic.

**Describe the solution you'd like**
- Add resin base to dRICH sensors, following the [S13361-3050NE-08 datasheet](https://www.hamamatsu.com/content/dam/hamamatsu-photonics/sites/documents/99_SALES_LIBRARY/ssd/s13361-3050_series_kapd1054e.pdf)
- Use the correct sensor thickness

**Comment by c-dilks** [comment]
@chchatte92 @alexander-kiselev @ajitkmaurya is this the right SiPM?

**Comment by alexander-kiselev** [comment]
which one? I see no attachment

________________________________

**Comment by c-dilks** [comment]
S13361-3050NE-08
https://www.hamamatsu.com/content/dam/hamamatsu-photonics/sites/documents/99_SALES_LIBRARY/ssd/s13361-3050_series_kapd1054e.pdf
I suppose we could also use S13361-3050AE-08 which AFAIK just has a different base pinout and form factor.
(BTW, if you are reading this as an email it's better to view the issue on Github at https://github.com/eic/epic/issues/111)

**Comment by alexander-kiselev** [comment]
Hi Chris,

  historically I first used the specs of S13361-3050AE-08, but for our purposes AE and NE are the same type.
Roberto would know better what they are considering to use.

  Cheers,
    Alexander.

________________________________

**Comment by JunhuaiXu** [comment]
structure of S13361-3050NE-08

Number of channels: 64 (8 × 8)

sensor thickness=real thickness + resin=1.35mm
sensor size: 25.8mm



```
<!-- sensor geometry; model = S13361-3050NE-08 SiPM -->
<constant name="DRICH_sensor_size"           value="25.8*mm"/> <!-- full length of the sensor side FIXME: resin base should be this size -->
<constant name="DRICH_pixel_gap"             value="0.2*mm"/> <!-- size of gaps between adjacent pixels AND gaps between edge pixels and sensor side -->
<constant name="DRICH_sensor_sensitive_size" value="DRICH_sensor_size - DRICH_pixel_gap"/> <!-- side length of photosensitive surface (to be segmented) -->
<constant name="DRICH_sensor_thickness"      value="1.35*mm"/>  <!-- sensor thickness FIXME: use the real thickness + resin -->
<constant name="DRICH_num_px"                value="3584"/>       <!-- number of pixels along one side of the sensor -->
<constant name="DRICH_pixel_size"            value="3.0*mm"/>  <!-- a single SiPM pixel size -->
<constant name="DRICH_pixel_pitch"           value="DRICH_pixel_size + DRICH_pixel_gap"/>  <!-- center-to-center distance between SiPMs in a 8x8 panel -->
```

**Comment by alexander-kiselev** [comment]
Hello colleagues! If we are planning to manipulate with the optical photons inside of the sensors, it may make sense to set up a meeting and discuss how to do this "properly". In particular, it is clear that part of the reflected light loss at the air-to-resin and resin-to-silicon boundaries (~15% at normal incidence, taken together) is effectively accounted in the provided QE curve. Cheers! Alexander.
________________________________

**Comment by c-dilks** [comment]
Yes, definitely. If these effects are accounted for in the QE curve, should we just be counting all photons that are incident on the silicon surface? We apply the QE downstream in a reconstruction algorithm.

Anyway, the issue that @JunhuaiXu is working on here is adding a resin base to the sensors, and also is related to #175, for adding material equivalent to bases and cooling.

**Comment by alexander-kiselev** [comment]
Hi Chris,

  I think we may run into trouble at very shallow angles, where the reflected-to-refracted ratio may become very different. All I'm saying is that it would be best if somebody spends his / her time, and comes up with definitive conclusions / recipes how to handle this situation correctly. Would be nice to have a direct PDE measurement vs incident angle, by the way.

  Cheers,
    Alexander.

________________________________

**Comment by JunhuaiXu** [comment]
<constant name="DRICH_sensor_thickness"      value="1.34*mm"/>  
<constant name="DRICH_resin_thickness"      value="0.1*mm"/>  

......


<documentation level="10">
##### Sensor module
- dimensions:
  - `side`: side length of the square module
  - `thickness`: thickness of the sensor module
  - `gap`: provides room between the squares, to help prevent them from overlapping
  - note: the value of `side` will determine how many sensors there are, since the
    sensor placement algorithm will try to place as many as it can in the specified
    spherical patch below
</documentation>
<module
  material="AirOptical"
  surface="SensorSurface_DRICH"
  vis="DRICH_sensor_vis"
  side="DRICH_sensor_sensitive_size"
  thickness="DRICH_sensor_thickness"
  gap="0.3*mm"
  />
  <resin
  material="Epoxy"
  surface="SensorSurface_DRICH"
  side="DRICH_sensor_sensitive_size"
  thickness="DRICH_resin_thickness"
  />

**Comment by JunhuaiXu** [comment]
<img width="539" alt="image" src="https://user-images.githubusercontent.com/110751396/205607788-508e5226-8a75-474c-80d7-c78fcdef056e.png">
