### ISSUE TITLE
dRICH: add airgap `Cone` between aerogel and filter

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#116]
**Is your feature request related to a problem? Please describe.**
The small gap between the aerogel and filter should be made of air; currently it is C2F6 because there is no defined volume between the aerogel and filter, other than the mother gas volume.

**Describe the solution you'd like**
This can be done by adding a `Cone` of air, similar to the aerogel and filter `Cone`s (e.g., `aerogelSolid`). With this being the 3rd such `Cone`, the repeated code can likely be generalized.

**Describe alternatives you've considered**
Leave as is; probably won't change anything significantly.

**Comment by JunhuaiXu** [comment]
`
<documentation level="10">
### dRICH: ***d***ual ***R***ing ***I***maging ***Ch***erenkov detector
</documentation>
<detector
  id="ForwardRICH_ID"
  name="DRICH"
  type="epic_DRICH"
  readout="DRICHHits"
  gas="AirOptical"
  material="Aluminum"
  vis_vessel="DRICH_vessel_vis"
  vis_gas="DRICH_gas_vis"
  >
`

**Comment by JunhuaiXu** [comment]
![Image](https://user-images.githubusercontent.com/110751396/204808573-8bafb3fd-7561-4622-8e45-bf9ab58e8a5c.png)
