### ISSUE TITLE
Fix the length of the Imaging Barrel ECAL

### ISSUE THREAD

**Issue by mariakzurek** [eic/epic#152]
**Is your feature request related to a problem? Please describe.**
The length of the imaging barrel in the negative z direction should be 257 cm and 177.5 cm in positive direction (from IP) + electronics like in https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html

**Describe the solution you'd like**
Currently the calorimeter length is set to:
`EcalBarrel_length              =      525.000 = EcalBarrelForward_zmax + EcalBarrelBackward_zmax`

So either the envelope would need to be changed or the length `z` and `offset` in the detector description  https://github.com/eic/epic/blob/main/compact/ecal_barrel_interlayers.xml (currently assigned to `EcalBarrel_length` and `EcalBarrel_offset` respectively  https://github.com/eic/epic/blob/main/compact/ecal_barrel_interlayers.xml#L99).

**Comment by mariakzurek** [comment]
@wdconinc, I could assign in [ecal_barrel_interlayers.xml](https://github.com/eic/epic/blob/main/compact/ecal_barrel_interlayers.xml) the length `z` to abs(z_min) + z_max from [the database](https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html), but I'm not sure what to do with the offset (i.e., how much calo is shifted from (0,0,0)). I could set just (z_min + z_max)/2, but it will be then independent from the global offset set in `definitions.xml`

**Comment by wdconinc** [comment]
To be honest, I have no idea what the offset means in the detector parameter table. In the geometry, and for barrel detectors, it is whether the detector's center should be shifted from the interaction point or not. That is what `EcalBarrel_offset` is set to, for both calorimeter options: assuming `EcalBarrel_zmin` and `EcalBarrel_zmax`, what is the corresponding shift.

I think in your case, I'd probably recommend to simply use an [offset](https://github.com/eic/epic/blob/main/compact/ecal_barrel_interlayers.xml#L99) of zero (ignoring what is defined by the definitions file). You could then use the length to be `2*min(EcalBarrel_zmin,EcalBarrel_zmax)` and it would always fit. Or you could just define a local offset as you write, as `(EcalBarrel_zmin - EcalBarrel_zmax) / 2`.

There is no requirement to use all the dimensions set in the definitions file, just that when you go outside the volume that is defined there it is going to be your fault ;-)
