### ISSUE TITLE
When built XML files are copied to ecce directory

### ISSUE THREAD

**Issue by DraTeots** [eic/epic#16]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch -  main

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. make install 

### Expected Result: (what do you expect when you execute the steps above)

```
/home/romanov/eic/soft/epic/share/epic/*xml
```

### Actual Result: (what do you get when you execute the steps above)

But I have

```
/home/romanov/eic/soft/epic/share/ecce
```

**Comment by wdconinc** [comment]
Resolved by #17.
