### ISSUE TITLE
Propagate cross section to the simulation

### ISSUE THREAD

**Issue by obylund** [eic/epic#169]
**Is your feature request related to a problem? Please describe.**
When running npsim on a hepmc file (using the epic geometry), the event-by-event cross section is not transferred from hepmc to the simulated file.

**Describe the solution you'd like**
Read the GenCrossSection value event by event in the hepmc file and store it as an event property in the simulated file.

**Describe alternatives you've considered**
I think we should have this.

**Additional context**
Thanks. Let me know if I can be of use, though I do not have much experience of the software yet. This is an important issue for me.

**Comment by veprbl** [comment]
Please file to
https://eicweb.phy.anl.gov/EIC/NPDet
or
https://github.com/AIDASoft/DD4hep

**Comment by obylund** [comment]
> 

Thanks. Opened an issue in DD4hep.

**Comment by wdconinc** [comment]
Tracking at https://github.com/AIDASoft/DD4hep/issue/988

**Comment by veprbl** [comment]
No actionable items for this repo, let's close.
