### ISSUE TITLE
dRICH: add sensor services

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#175]
**Is your feature request related to a problem? Please describe.**
Request from Roberto Preghenella:

> I would like to ask if there is any chance to try putting some services also behind the dRICH sensor plane.
> somewhat in the same fashion as done for the pfRICH.
>
> my feeling from your drawings is that there is not enough room to put services and electronics behind the dRICH sensors. it is true that a real model for that is still missing, but a possible start is what was put in the drawings for the mRICH. Namely a 20 cm box behind the sensors that represents the current-guess for space needed for services and electronics.
>
> would it be possible to have a look at that?
> I have a drawing that I attach to this email to explain better my message.
my rough estimate based on numbers extracted from this drawing (need to see how it is in 3D) is that there is a lack of 10 cm in space with the current optics layout. 

![Image-DR4HT1](https://user-images.githubusercontent.com/7843751/194400649-05f318ee-fb2c-44d4-a441-3e1779f681c9.png)

**Comment by preghenella** [comment]
hi @c-dilks thanks for opening this issue.
can one not increase the thickness of the sensor volume to achieve what I am asking in a quick-and-dirty way?

**Comment by c-dilks** [comment]
If we try to extrude the sensor bases, they might start overlapping each other. I think an easier approach is to add a `Sphere`, placed with the same center as the sphere used to generate the sensor positions. We can make the inner and outer radii such that it's 20 cm thick, and the outer radius can be made to be as close to the sensor bases as possible.

Then we can take the boolean `IntersectionSolid` of this `Sphere` and the gas volume, cutting the shape so it fits in the vessel. Since we will have to move the sensors forward by ~10 cm, the optics will have to be re-tuned, but that will be straightforward.

What material(s) should we use? We could also make concentric `Sphere`s, if we want layers of materials. By comparison, the pfRICH currently uses 3 sheets of aluminum, 0.5 cm thick, equally spaced spanning 15 cm behind the sensor plane, with air volumes between.

**Comment by preghenella** [comment]
as a start I would not mind of overlaps, but just try to understand how much the readout could violate the boundaries of the dRICH envelope. that is why I was suggesting to increase the dz of the sensor box.
a possible readout block might have something like a 4x4 cm² of area behing the 5x5 cm² of the sensors, similar to this pic
![image](https://user-images.githubusercontent.com/5835025/194618285-3e752cc9-6a44-4265-9d1f-dfa8ee6fdd98.png)

your Sphere approximation might work to look into the issue, but I would not cut it to fit in the envelope for the time being.
