### ISSUE TITLE
Barrel ECal: missing inner surface material

### ISSUE THREAD

**Issue by veprbl** [eic/epic#179]
According to the latest menagerie (https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html), there should be a 1.95 thick piece of Aluminum in front of the ECals.

Outer support material is also missing.

cc @mariakzurek

**Comment by sly2j** [comment]
I think this should only impact the SciGlass but not the Imaging ECal as the latter is self-supporting. This is also the case in the detector table.

@veprbl: do you want to implement this for the SciGlass either as part of the main detector or as a separate support frame?

**Comment by veprbl** [comment]
> @veprbl: do you want to implement this for the SciGlass either as part of the main detector or as a separate support frame?

I don't know this yet. It's unclear to me whether this material is part of the wedge box, or a separate construction. I will need to confirm this with the project.

If this is just a separate tube, we might just inline it as GDML.
