### ISSUE TITLE
Fix outer tracker service routing overlaps

### ISSUE THREAD

**Issue by sly2j** [eic/epic#208]
The outer tracker service routing overlaps the pfRICH (and probably mRICH) in the negative end, and the 90 degree turn conflicts with the imaging ecal in the positive end. I suggest (pragmatically) to:
* shorten second projective cone on the negative end to the face of the pfRICH, and have a discontinuous step to a cylinder outside of the pfRICH/mRICH
* replace 90 degree turn with an extension of the cone near the dRICH in the positive end for the dRICH end

**Comment by c-dilks** [comment]
Resolving this would also close https://github.com/eic/epic/issues/159
