### ISSUE TITLE
SciGlass wedge box should be 6 mm apart

### ISSUE THREAD

**Issue by veprbl** [eic/epic#214]
Quoting Elke:
> The correct numbers from the CAD are 3mm Al from the side wall 6mm Air 3mm Al side wall from the next box

In the current geometry, I can fit a slab of ~5.6 mm between the tower sectors with carbon supports and ~6.2 mm with carbon fiber removed. I've requested a 3D model for the wedge box to see how they manage to fit it.

**Comment by wdconinc** [comment]
Closed with #258 .
