### ISSUE TITLE
CI on main is broken

### ISSUE THREAD

**Issue by veprbl** [eic/epic#229]
```
Compact          ERROR ++ FAILED    to convert subdetector: ZDCEcal: dd4hep: Evaluator::Object : unknown variable : ZDCEcal_ID : value=ZDCEcal_ID [Evaluation error]
[775](https://github.com/eic/epic/actions/runs/3275851300/jobs/5391200907#step:4:777)
```

**Comment by veprbl** [comment]
cc @rahmans1 @ajentsch

**Comment by ajentsch** [comment]
Looking into it. Not sure what the problem is.

**Comment by wdconinc** [comment]
This is a timing issue: the ZDC had to go through a backwards incompatible change (again), so that had to go through in ip6 first, get merged, then go through checks in epic, and is now merged.

**Comment by wdconinc** [comment]
The next time this has to happen again, we will have merged the repositories.
