### ISSUE TITLE
Respect $BEAMLINE_PATH

### ISSUE THREAD

**Issue by veprbl** [eic/epic#23]
**Is your feature request related to a problem? Please describe.**
The ecce compact file does not rely on BEAMLINE_PATH set in
https://github.com/eic/ip6/blob/5fe0178ea0fc6a490c776e02ff750693a60f576f/templates/setup.sh.in#L4
instead, some ad-hoc symlink to ip6 is used.

**Describe the solution you'd like**

```diff
diff --git a/templates/epic.xml.jinja2 b/templates/epic.xml.jinja2
index 5e30dbe..0e08a0c 100644
--- a/templates/epic.xml.jinja2
+++ b/templates/epic.xml.jinja2
@@ -44,8 +44,8 @@
       The ip6 (or other ip) defines should be included first.
       These files have only a define tags.
   </documentation>
-    <include ref="ip6/definitions.xml" />
-    <include ref="ip6/far_forward/fields_{{ pbeam | default("275", true) }}.xml" />
+    <include ref="${BEAMLINE_PATH}/ip6/definitions.xml" />
+    <include ref="${BEAMLINE_PATH}/ip6/far_forward/fields_{{ pbeam | default("275", true) }}.xml" />
     <include ref="compact/definitions.xml" />
   </define>
 
```

If the variable is not set, DD4hep will fail:
```
RunPlugin        ERROR ++ Exception while executing plugin DD4hep_CompactLoader:
                dd4hep: Severe error during environment lookup of ${BEAMLINE_PATH}/ip6/definitions.xml Evaluator::Object : unknown variable : ${BEAMLINE_PATH}
```

There doesn't seem to be a way to provide a default value for `${BEAMLINE_PATH}` in DD4hep evaluator, despite some similar feature already working:
https://github.com/AIDASoft/DD4hep/blob/02c6d5ac04c187f37631f9f15ca6c1c08452d992/examples/LHeD/compact/compact_Lhe_dip_sol_ell.xml#L34-L39

**Describe alternatives you've considered**
 - Merge ip6 into this repository

**Additional context**
Some upstream discussion in https://github.com/AIDASoft/DD4hep/issues/934

**Comment by wdconinc** [comment]
I have a deep instinctive aversion to environment variables (somehow it's only physicists' software that seems to require them). But this may be one of those cases we can't avoid; because I dislike having to carefully arrange repositories even more.

**Comment by DraTeots** [comment]
Put IP6 as a git submodule maybe?

**Comment by DraTeots** [comment]
IMO the best way is to merge the repositories and painfully fix all places. Pain is temporary, Glory is forever.

**Comment by wdconinc** [comment]
Submodule: no, doesn't work with the current structure (it's not the ip6 repo that needs to be included in the epic repo, but a subdirectory of the ip6 repo needs to installed into a part of the epic install tree). Also, submodules are hardly ever a good solution.

**Comment by DraTeots** [comment]
1. It makes location of ip6 more controllable and avoids using environment variables

> it's not the ip6 repo that needs to be included in the epic repo, but a subdirectory of the ip6 repo needs to installed into a part of the epic install tree

2. Add nested ip6 to epic cmake so now its build is controllable also

Then how it differs from merging repos? - probably not too much...
