### ISSUE TITLE
Geant4VolumeManager INFO  +++   Bad volume Geant4 Path: /AV_836!MPGDDIRC_0_31#31!component0_0#0

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#234]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (`main` for latest released): `main`
- Which revision (`HEAD` for the most recent): 
- Any specific OS or system where the issue occurs? eic-shell
- Any special versions of ROOT or Geant4? eic-shell

### Steps to reproduce: (give a step by step account of how to trigger the bug)
See, e.g. https://eicweb.phy.anl.gov/EIC/benchmarks/physics_benchmarks/-/jobs/1093877#L900

No reproducer yet.

### Expected Result: (what do you expect when you execute the steps above)
Expect no warnings.

### Actual Result: (what do you get when you execute the steps above)
Getting warnings.

**Comment by mposik1983** [comment]
@wdconinc I just took a closer look at some ddsim events I generated and I do see this message in the output as well. I must have missed it the first time due to all of the other output text that get printed.

**Comment by mposik1983** [comment]
@sly2j That was my first thought as well and where I was going to start. I will try to find some time today and take a shot at fixing it myself, but I may need some help in which case I'll take you up on your offer. I'll let you know tonight where I am. Thanks!

**Comment by wdconinc** [comment]
This was resolved by #241
