### ISSUE TITLE
Separate global magnetic field from solenoid materials

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#259]
**Is your feature request related to a problem? Please describe.**
The `tracking_only` geometry is currently a possible detector configuration, but it is not really useful for quick tracking simulations since no magnetic field is included. Most of the `*_only` configurations were originally developed primarily for visualization purposes. Adding a magnetic field is not affecting that use case at all.

**Describe the solution you'd like**
There should be a quick tracking simulation geometry that has no calorimetry or other material that isn't tracking planes. In particular, it should not include the solenoid material. We should probably pull the magnetic field out of the solenoid geometry and include it separately.

**Describe alternatives you've considered**
It may also be possible to include the magnetic field directly in the top level and have a definition that can be used to set the strength to zero. There may be a benefit (e.g. RICH studies) to being able to set the field to zero without having to edit `solenoid.xml`.

Tagging for comments: @veprbl @c-dilks @DraTeots

**Comment by simonge** [comment]
For completeness it would also be nice to see this available for far-backwards and other beamline studies.
