### ISSUE TITLE
Reducing tolerance to 0.01 mm causes a _**LOT**_ of `SciGlassModule` overlaps to be detected

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#27]
Reducing tolerance to 0.01 mm causes a _**LOT**_ of `SciGlassModule` overlaps to be detected

_Originally posted by @c-dilks in https://github.com/eic/epic/issues/26#issuecomment-1199892875_

**Comment by c-dilks** [comment]
You can cherry pick https://github.com/eic/epic/pull/26/commits/193b444d10c68d3becea9ad07fb11ff20c7d691d if you want a quick check

**Comment by veprbl** [comment]
@wdconinc The current SciGlass geometry based on a design inspired by PANDA calorimeter is outdated – the problematic tilt in phi was deemed infeasible for construction. I am working on replacing it to match the current design which is much simpler. For the time being, we could disable the overlap checking for it.

**Comment by wdconinc** [comment]
The overlaps are already below the tolerance we have, so there's no need to disable them.

**Comment by veprbl** [comment]
I was assuming that the lower tolerance was desired, but could not be applied because of this issue.

**Comment by wdconinc** [comment]
The lower tolerance may be useful but not as part of CI. It is simply too slow. Moreover, this is the TGeo overlap check where even a lower tolerance misses many overlaps because of inherent limitations. The geant4 check is more likely to catch those overlaps but runs even more slowly... For Athena we ran the full overlap checks offline since they would take up to 8 hours to complete. We may need to do something similar here, or we should run the overlap checks on individual subsystems (which we didn't have for Athena at the time).

**Comment by wdconinc** [comment]
I mainly posted this because I am curious where the overlaps are coming from. I must have messed up my math somewhere since I attempted to code it up without any possibility for overlaps (if no hard coded dimensions are used).

**Comment by veprbl** [comment]
The #45 is the first step with this

**Comment by veprbl** [comment]
Works with `checkOverlaps -t 0.0000001` now
