### ISSUE TITLE
Forward_TOF causing SurfaceError-s in reconstruction

### ISSUE THREAD

**Issue by DraTeots** [eic/epic#286]
There was a problem with reconstruction described in issues https://github.com/eic/EICrecon/issues/319 and https://github.com/eic/EICrecon/issues/319. During reconstruction we got errors that crashed tracking: 

```
SurfaceError: Global to local transformation failed: position not on surface.
```

After fixing error handling in EICrecon and adding verbose warning on SurfaceError-s, now I see that the only Forward TOF hits causing problems. Example from reconstruction output: 

```
2022-11-10 00:13:38.154] [tracking:CentralTrackerSourceLinker] [warning] Can't convert globalToLocal for hit: vol_id=85065850 det_id=122 CellID=18446743850456318074 x=-5.2 y=-518.9375 z=1914.85

[2022-11-10 00:13:39.185] [tracking:CentralTrackerSourceLinker] [warning] Can't convert globalToLocal for hit: vol_id=327802 det_id=122 CellID=562065190486138 x=20.6 y=625.1875 z=1924.95
```

Checked branches: 
- master
- 22.11.0

@yezhenyu2003

**Comment by wdconinc** [comment]
```
2022-11-10 00:13:38.154] [tracking:CentralTrackerSourceLinker] [warning] Can't convert globalToLocal for hit: vol_id=85065850 det_id=122 CellID=18446743850456318074 x=-5.2 y=-518.9375 z=1914.85
```
cellID = 0xFFFFFFCC0512007A

```
[2022-11-10 00:13:39.185] [tracking:CentralTrackerSourceLinker] [warning] Can't convert globalToLocal for hit: vol_id=327802 det_id=122 CellID=562065190486138 x=20.6 y=625.1875 z=1924.95
```
cellID = 0x0001FF320005007A

**Comment by wdconinc** [comment]
Maybe because the endcap TOF falls outside of the tracking region defined [here](https://github.com/eic/epic/blob/main/compact/definitions.xml#L626)...
```
    <constant name="EcalEndcapN_zmin"               value="174*cm"/>   <!-- Currently fix value hardcoded -->

    <constant name="tracker_region_rmax"   value="EcalBarrel_rmin"/>
    <constant name="tracker_region_zmax"   value="EcalEndcapN_zmin"/>
```

@sly2j We need to be able to define asymmetric tracking regions. Do you know if that's possible?

**Comment by wdconinc** [comment]
Or maybe not... The `tracker_region_zmax` is only used by the particle handler, not passed to Acts.

**Comment by DraTeots** [comment]
IDK if this makes it easier to guess what happens: 

In reconstruction failure happens here:

https://github.com/eic/EICrecon/blob/main/src/algorithms/tracking/TrackerSourceLinker.cc#L84

What is the algorithms around it: 

1 - We look through all surfaces and for a surface that correspond to hit (It actually finds the surface and passes the code below) : 

```c++
auto surfaceMap = m_acts_context->surfaceMap();

// ...

const auto is = surfaceMap.find(vol_id);
if (is == m_acts_context->surfaceMap().end()) {
     m_log->warn(" WARNING: vol_id ({})  not found in m_surfaces.", vol_id );
     continue;
}
```

2 - Error happens when we try to find a point on surface and convert to local coordinates

```c++
pos = surface->globalToLocal(
                    Acts::GeometryContext(),
                    {hit_pos.x, hit_pos.y, hit_pos.z},
                    {0, 0, 0}).value();
```

3 - The internal error and code is related to a case where point is not found on surface.

**Comment by Simple-Shyam** [comment]
I checked that the hits are on the TOF surface.
![hitsrz_dd4hep](https://user-images.githubusercontent.com/15985144/201173988-69f1f939-2c02-4f0e-a530-34ae98cab647.png)

**Comment by wdconinc** [comment]
The Acts extension in DD4hep is incomplete for `src/CompositeTracker.cpp`. Only half the work of supporting Acts was done. We probably need something like this (from `src/TrapEndcapTracker_geo.cpp`) in the area where the TOF sensors are placed.
```
    Acts::ActsExtension* layerExtension = new Acts::ActsExtension();
    layerExtension->addType("sensitive disk", "layer");
    for (xml_coll_t lmat(x_layer, _Unicode(layer_material)); lmat; ++lmat) {
      xml_comp_t x_layer_material = lmat;
      xmlToProtoSurfaceMaterial(x_layer_material, *layerExtension, "layer_material");
    }
    layer_element.addExtension<Acts::ActsExtension>(layerExtension);
```

**Comment by wdconinc** [comment]
Or you could wait for @rahmans1 to complete the conversion to Acts-20.

**Comment by Simple-Shyam** [comment]
@nschmidtALICE @yezhenyu2003   you can follow this discussion. We are working on it.
