### ISSUE TITLE
Addition of detailed LFHCal geometry

### ISSUE THREAD

**Issue by FriederikeBock** [eic/epic#315]
**Is your feature request related to a problem? Please describe.**
The current implementation of the LFHCal geometry is too approximate, we should put the correct tower/module assemblies with corresponding active/inactive material.

**Describe the solution you'd like**
I started implementing the correct 8M and 4M module geometries (see pictures) below. This all works fine for the placement of a few modules, but full detector fails building. 

full code: https://github.com/FriederikeBock/epic/tree/lfhcal-dev

**Additional context**

![module](https://user-images.githubusercontent.com/26482042/203172746-f990f629-ecbc-43c6-9c99-29e971dc4148.png)
![moduleDetail](https://user-images.githubusercontent.com/26482042/203172748-94123e1a-c07e-4ebb-ae2a-5867eb296acf.png)
![MultModules](https://user-images.githubusercontent.com/26482042/203172750-fb6ef9f1-1cde-45a9-a1b9-d386e05a50d6.png)
![scintplatewithTi02sep](https://user-images.githubusercontent.com/26482042/203172751-012d3bc8-a573-4d10-8146-c944b72484ae.png)
![two4MModules](https://user-images.githubusercontent.com/26482042/203172752-f2d06608-cf4b-4ecf-a4aa-dfc39970bd67.png)

Putting 1/2 of the full detector (~580 modules) . Fails when running:

`
dd_web_display --export install/share/epic/epic_lfhcal_only.xml
`

with 

`
[2022-11-21 15:44:43.208] [info] running in batch mode to export geometry 
Error in <TBufferFile::CheckCount>: buffer offset too large (larger than 1073741822)
Error in <TBufferFile::CheckCount>: buffer offset too large (larger than 1073741822)
Error in <TBufferFile::CheckCount>: buffer offset too large (larger than 1073741822)
Error in <TBufferFile::WriteByteCount>: bytecount too large (more than 1073741822)
Error in <TList::Clear>: A list is accessing an object (0x7fffb9a16780) already deleted (list name = TList)
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
`
I tried simplyfing the geometry already quite a bit but it still fails miserably and takes about 15min for the geom creation before it fails.

**Comment by wdconinc** [comment]
Implemented in #406 and #467
