### ISSUE TITLE
Refactor the DD4hep/Acts integration for acts@20.0.0: and dd4hep@1.21:

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#34]
**Is your feature request related to a problem? Please describe.**
There have long been some ergnomics issues with Acts integration in DD4hep geometries. These are now addressed in Acts (tentatively targeted for v20.0.0) and build on some recent changes in DD4hep (as of v1.21). For details see https://github.com/acts-project/acts/pull/1257. As is common for Acts, this is backwards incompatible so we're essentially stuck on Acts v19.6.0 until we make the required changes.

**Describe the solution you'd like**
Instead of segments like ([TrapEndcapTracker_geo.cpp](https://github.com/eic/epic/blob/d1336e5ff1b1f7adfe3defbd03fe7ac0cc1f1035/src/TrapEndcapTracker_geo.cpp#L58))
```cpp
  // ACTS extension
  {
    Acts::ActsExtension* detWorldExt = new Acts::ActsExtension();
    detWorldExt->addType("endcap", "detector");
    // Add the volume boundary material if configured
    for (xml_coll_t bmat(x_det, _Unicode(boundary_material)); bmat; ++bmat) {
      xml_comp_t x_boundary_material = bmat;
      Acts::xmlToProtoSurfaceMaterial(x_boundary_material, *detWorldExt, "boundary_material");
    }
    sdet.addExtension<Acts::ActsExtension>(detWorldExt);
  }

  // snip

    Acts::ActsExtension* layerExtension = new Acts::ActsExtension();
    layerExtension->addType("sensitive disk", "layer");
    for (xml_coll_t lmat(x_layer, _Unicode(layer_material)); lmat; ++lmat) {
      xml_comp_t x_layer_material = lmat;
      xmlToProtoSurfaceMaterial(x_layer_material, *layerExtension, "layer_material");
    }
    layer_element.addExtension<Acts::ActsExtension>(layerExtension);
```
we would replace this with segments in xml, e.g.
```xml
    <detector
      id="TrackerEndcapP_0_ID"
      name="TrackerEndcapP_Inner"
      type="epic_TrapEndcapTracker"
      readout="TrackerEndcapHits"
      vis="TrackerVis"
      reflect="false">
      <type_flags type="DetType_TRACKER + DetType_ENDCAP" />
      <boundary_material surface="inner" binning="binPhi,binZ" bins0="mat_sol_bPhi" bins1="mat_sol_bZ"/>

      <!-- snip -->

    </detector>
```
and
```xml
  <plugins>
    <plugin name="DD4hep_ParametersPlugin">
      <argument value="TrackerEndcapP_Inner"/>
      <argument value="passive_layer: bool = false"/>
    </plugin>	
  </plugins>
```
Further details in the [new dd4hep plugin documentation page](https://acts.readthedocs.io/en/latest/plugins/dd4hep.html).

**Describe alternatives you've considered**
For the time being we can remain pinned on Acts v19.6.0 without too many issues, but based on past experience we need a plan in place for transition since incompatible changes pile up quickly.

**Comment by wdconinc** [comment]
FYI @sly2j, this is both nice to see and annoying to have to deal with right now :-)

**Comment by wdconinc** [comment]
Reference to where this was done on ODD: https://gitlab.cern.ch/acts/OpenDataDetector/-/merge_requests/31

**Comment by wdconinc** [comment]
@DraTeots I've just added milestone 22.12.0 to this, which is to say this would tentatively go in after this production but around the December timeframe. We probably need to have this coordinated with eicrecon tracking as well.

**Comment by DraTeots** [comment]
Thanks for the updates. At one point I made a branch https://github.com/eic/EICrecon/tree/acts20 which did the transition so it will be resurrected as needed. 

Isn't there v21 coming already?

**Comment by DraTeots** [comment]
https://github.com/acts-project/acts/releases/tag/v21.0.0

**Comment by wdconinc** [comment]
Acts 21 is not as invasive as Acts 20.

**Comment by DraTeots** [comment]
Yes, but wouldn't it be better to switch to the latest version and forget about it for longer?

**Comment by wdconinc** [comment]
It will indeed be better to switch to the latest version. I have been keeping a close eye on all new versions, including what (not just EIC) reconstruction codes have to expect in terms of breakage because I have been typically the one to add the new Acts versions to spack, including testing them for build failures on various platforms and dependencies. I have been the one upgrading juggler from Acts 8.3 through Acts 19.7. Together with 8 to 9, the change from 19 to 20 is comparatively a lot of work. Most other transitions are a few interfaces here or there, typically with a lot of good examples out there that are comparable to what we are doing in EIC. There is no such comparable example for 19 to 20, so we are on our own. So, we can say that we will upgrade to 21, but the work is in the transition to 20, in particular the one PR linked in the original description. This one PR is also the reason why there are still backports happening to the 19 version series: we are hardly the only ones who are not able to make that change on short notice.

All this to say: yes, we should upgrade to the newest version, but no, there are no issues expected with 20 to 21 so it is not really worth mentioning.

**Comment by wdconinc** [comment]
And by a lot of work from 19 to 20, I mean in the DD4hep geometry, not the reconstruction code (where the level of changes is again trivial). The entire model of geometry modeling for DD4hep geometries changes, with no backwards compatibility.

**Comment by rahmans1** [comment]
> And by a lot of work from 19 to 20, I mean in the DD4hep geometry, not the reconstruction code (where the level of changes is again trivial). The entire model of geometry modeling for DD4hep geometries changes, with no backwards compatibility.

If there is no one taking this up immediately, I am tempted to volunteer. Is there a eic-container with the relevant acts and dd4hep versions? Do you view this as a single PR or multiple PRs for each subsystem?

**Comment by wdconinc** [comment]
> I am tempted to volunteer.

Appointed! There's a timeline, completion by start of December.

> Is there a eic-container with the relevant acts and dd4hep versions?

https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/343 creates https://hub.docker.com/layers/eicweb/jug_dev/unstable-mr-290-343/images/sha256-c7b87328c39720129a726f6dce77b71b96024334bdc9294c00e2ef0eee3b45c0?context=explore. Because the geometry (and other components of the container) fails to compile, no jug_xl container is created, though.

> Do you view this as a single PR or multiple PRs for each subsystem?

Likely a single PR because the current approach won't work anymore in Acts 20, so we have to switch everything over at one if we want to have a working system. It will require that we change eic-shell to acts@20 at the same time (or just before) we merge the changes to the geometry.

**Comment by wdconinc** [comment]
> completion by start of December.

Tentatively :-)
