### ISSUE TITLE
dRICH: reduce aerogel radius and recover full eta acceptance

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#353]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (`main` for latest released): `main`

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. set `DRICH_debug_optics` to `1` in `drich.xml`
2. run `simulate.py -t12 -n10` from `drich-dev` to produce images like below

### Expected Result: (what do you expect when you execute the steps above)
Something at least as good as #24 

### Actual Result: (what do you get when you execute the steps above)
High eta reflected photons miss the sensors, and our current acceptance is limited to eta<2.3
![2023-01-19-155636_796x861_scrot](https://user-images.githubusercontent.com/7843751/213562063-cea29767-78aa-4b34-8b31-3aac8b451385.png)

**Comment by c-dilks** [comment]
Degradation in optics since #24 likely caused by small envelope changes for 22.11 production preparation.

**Comment by chchatte** [comment]
After changing `DRICH_debug_optics` to 1; when I rebuild `epic`; the simulation fails. Complaining about that `Failed to access invalid PlacedVolume!`

**Comment by c-dilks** [comment]
My bad, https://github.com/eic/epic/pull/350 fixed this, but auto-merge never merged it.

**Comment by c-dilks** [comment]
Merged!
