### ISSUE TITLE
Treating ions in ddsim

### ISSUE THREAD

**Issue by michael-pitt** [eic/epic#355]
**Is your feature request related to a problem? Please describe.**
MC Generators with ions at the final state (e.g. BeAGLE #92) cannot use [DD4hep](https://github.com/AIDASoft/DD4hep)

**Describe the solution you'd like**
It seems that the https://github.com/AIDASoft/DD4hep/pull/920 should solve the problem.

**Describe alternatives you've considered**
For now, the only workaround is to change the status of the ions in the hepmc files (https://github.com/eic/eic-smear/issues/22) so that when `ddsim` is executed, these ions will not be handled to G4.

@wdconinc @KongTu @kkauder

**Comment by wdconinc** [comment]
Confirming that #920 resolves this problem on a sample file as attached.
