### ISSUE TITLE
Adding EOS folder to `eic-shell` setup

### ISSUE THREAD

**Issue by michael-pitt** [eic/epic#356]
**Is your feature request related to a problem? Please describe.**
When setting up `eic-shell` on lxplus.cern.ch, the mounted folder `/eos` is removed.

**Describe the solution you'd like**
Add `/eos` to `install.sh` (L186)

**Comment by veprbl** [comment]
This is a wrong repository for this issue. Needs to go to https://github.com/eic/containers.

**Comment by michael-pitt** [comment]
Thanks @veprbl, I've opened https://github.com/eic/containers/issues/1
