### ISSUE TITLE
Lumi Direct photon detector

### ISSUE THREAD

**Issue by aniakowalewska** [eic/epic#360]
**Is your feature request related to a problem? Please describe.**
Creation of Lumi direct photon calorimeter in far backward system of ePIC detector

**Describe the solution you'd like**
Cubic geometry with target shape: tungsten (lead) spaghetti 

**Additional context**
will sit around 50meters from ip

**Comment by aniakowalewska** [comment]
@wdconinc how I can assigned myself and my colleague to the above issue [I do not see such a possibiliy]?

**Comment by wdconinc** [comment]
@aniakowalewska I think you need to be a member of the EPIC Devs team, and I have added you now.

**Comment by aniakowalewska** [comment]
@wdconinc Thank you.
