### ISSUE TITLE
Simplify implementation of the EcalBackward

### ISSUE THREAD

**Issue by veprbl** [eic/epic#362]
The `HomogeneousCalorimeter_geo` implements various geometry options that we don't seem to use, but also some stuff that we do use is outright hardcoded:
https://github.com/eic/epic/blob/9eb69289d9f781b10f45109937fa2e3fca797b6b/src/HomogeneousCalorimeter_geo.cpp#L508-L517

There an issue with the readout structure for which a single field `module` is responsible for addressing the calorimeter cells:
https://github.com/eic/epic/blob/9eb69289d9f781b10f45109937fa2e3fca797b6b/src/HomogeneousCalorimeter_geo.cpp#L501-L502
That is not friendly towards `adjacencyMatrix` definition for clustering, see discussion in https://eic.cloud.mattermost.com/main/pl/oo3weu6ikbnf3fe8xh1okmw91e.

**Comment by wdconinc** [comment]
FYI @johnny8266 This relates to https://github.com/eic/epic/pull/332. I told you that hardcoding positions was going to be temporary only.
