### ISSUE TITLE
dRICH: update aerogel-region envelope

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#363]
**Is your feature request related to a problem? Please describe.**
Updated plan from GD/I; note this involves a doubling of the `snout_length`, which is under discussion. This could also involve placing the sensors in dedicated extruded "boxes", leaving azimuthal space for service routing.

![image](https://user-images.githubusercontent.com/7843751/218346867-48b95737-b002-45a4-a692-e4e67c6d521a.png)

**Comment by chchatte92** [comment]
Hello @c-dilks in the `main` branch I have commited aerogel radius as 90 cm with Athena like acceptance. 
commit ID: 22df3d9

**Comment by c-dilks** [comment]
Actually this issue is different; I linked your PR #374 to the other issue https://github.com/eic/epic/issues/353 (which means once the PR is merged the issue will be closed). This issue here has more to do with the 20 cm snout length vs. 39.5 cm... but let's wait for feedback from GD/I next week.

**Comment by c-dilks** [comment]
@chchatte92 should we just close this issue now, since we have been comparing well to the CAD designs?

**Comment by chchatte92** [comment]
Ah yes!
