### ISSUE TITLE
No usr/bin/python on ubuntu 22.04

### ISSUE THREAD

**Issue by DraTeots** [eic/epic#38]
- branch - main
- Fresh ubuntu 22.04

When building the detector: 

```
/usr/bin/env: /usr/bin/env: ‘python’‘python’: No such file or directory: No such file or directory
```

While there are solutions like: 

```
sudo apt install python-is-python3
```

I would advocate to fix it in epic repo by switching to python3. It is now everywhere

```
/usr/bin/env python3
```

**Comment by wdconinc** [comment]
Can you please file a bug report with steps to reproduce as requested by the template? Then we can identify which file is actually causing this.
