### ISSUE TITLE
"MultipoleMagnet rotation issue" may affect far-forward

### ISSUE THREAD

**Issue by veprbl** [eic/epic#388]
See https://github.com/AIDASoft/DD4hep/issues/1073 and https://github.com/eic/epic/blob/main/compact/far_forward/magnets.xml
Accoding to the report [1], there were some effect seen in ATHENA studies.

[1] https://eic.cloud.mattermost.com/main/pl/hgb66nt59ifuzrmia76bbugqny

**Comment by wdconinc** [comment]
Resolved by https://github.com/AIDASoft/DD4hep/pull/1080 which is backported into our default environment (https://eicweb.phy.anl.gov/containers/eic_container/-/merge_requests/585).
