### ISSUE TITLE
Imaging Barrel Calorimeter: add 200 um insensitive area around pixels

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#461]
**Is your feature request related to a problem? Please describe.**
All pixels have a 200 um insensitive area. This should be treated as insensitive, in simulation or digitization.

**Comment by wdconinc** [comment]
This could possible be done with clever irregular segmentation and dropping hits in digitization.

**Comment by veprbl** [comment]
Might make more sense to treat positions as uncorrelated and reject randomly based on the ratio of areas.

**Comment by wdconinc** [comment]
The thinking is to implement the actual sensor geometry, turbofan style.

**Comment by wdconinc** [comment]
Fixed by #490
