### ISSUE TITLE
Imaging Barrel Calorimeter: 6 AstroPix slots with 4 sensor layers only

### ISSUE THREAD

**Issue by mariakzurek** [eic/epic#468]
Implement AstroPix sensor layers in slots 1-3-5-6 only. 

This will most probably require also:
1) change in topo clustering algorithm to check not only the hits from neighbouring layers but also next-to-neighbouring layers
2) reoptimization of the imaging cluster parameters (lower min nb of hits, longer distances). I expect that the efficiency of clustering will drop significantly at first.

**Comment by wdconinc** [comment]
Resolved by https://github.com/eic/epic/pull/469
