### ISSUE TITLE
Change forward Hcal insert's readout to a hexagonal grid

### ISSUE THREAD

**Issue by rymilton** [eic/epic#496]
**Is your feature request related to a problem? Please describe.**
The forward HCal insert currently uses a square segmentation (CartesianGridXY) but should actually use a hexagonal grid segmentation.

**Describe the solution you'd like**
Create a hexagonal grid segmentation class and push it to ePIC. It would be similar to CartesianGridXY but would use hexagons instead of squares.

**Describe alternatives you've considered**
Push the segmentation class to the official DD4hep repository instead of to ePIC.

**Additional context**
The hexagon readout class currently does not exist in [DDCore](https://github.com/AIDASoft/DD4hep/tree/master/DDCore).

**Comment by rymilton** [comment]
Any input on where to push the files? If in the epic repository, should I put it somewhere specific to separate it from the detector files?

**Comment by wdconinc** [comment]
This should really go into DD4hep, not ePIC. It is generally applicable.

**Comment by rymilton** [comment]
Sure, I'll try doing that. I've never made changes to DD4hep before so I might need some help but I'll ask about that in the Helpdesk channel.

**Comment by rymilton** [comment]
Changing issue to adjusting the readout style of the insert, rather than implementing the segmentation class.

**Comment by rymilton** [comment]
Dependent on the creation of the hexagonal grid segmentation class in [DD4hep](https://github.com/AIDASoft/DD4hep). This completion of this issue is blocked until then.

**Comment by veprbl** [comment]
It is probably a good idea to just implement hexagonal tiles as volumes. Segmentations in DD4hep are well applicable to fine grids or preliminary designs. Design of the forward insert is already very mature. The only tricky part with volumes is that you'd need to use binary operations on volumes to create truncated tiles for the edges.

**Comment by veprbl** [comment]
Upstream PR https://github.com/AIDASoft/DD4hep/pull/1161

**Comment by wdconinc** [comment]
Hexagonal (and staggered cartesian) grids are now in `eic-shell`: 
```console
jug_xl> wdconinc@menelaos:~/git/epic$ ls /usr/local/include/DDSegmentation/HexGrid.h 
/usr/local/include/DDSegmentation/HexGrid.h
```
Thanks to @sebouh137 for the upstream contribution.

**Comment by rymilton** [comment]
Apologies for the delay on this. Working on implementing it now.

Additionally, the latest insert design has 10 tungsten layers instead of the 4 that are currently in the simulation, so I'll correct this.

**Comment by wdconinc** [comment]
Feel free to make two PRs so they can be reviewed independently.

**Comment by rymilton** [comment]
Layer numbering changed to Issue #546 .
