### ISSUE TITLE
Jinja2 expansion xml files should go to CMAKE_CURRENT_BINARY_DIR

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#54]
**Is your feature request related to a problem? Please describe.**
Users may `make` the epic code and end up with an `epic.xml` file in their source dir. They may do something with this file, which refers to environment variables. That may lead to confusing results.

**Describe the solution you'd like**
With produced xml files in the build directory, it is less likely that they would be used inadvertently assuming they work from the source dir top level.

**Describe alternatives you've considered**
Alternative is not changing.

**Comment by veprbl** [comment]
All build products should always go to the build directory. That helps to prevent them from being committed to the repo.

**Comment by wdconinc** [comment]
Totally agree! This was backwards compatibility when we switched from one ecce.xml in the repository to a template with build products. The benchmarks are still using a crazy installation scheme where we are running against a non-installed version in its source directory.

So, yes, and for every rule there's an exception that may or may not have been a good idea at the time ;-)

**Comment by wdconinc** [comment]
Depends on: https://eicweb.phy.anl.gov/EIC/benchmarks/common_bench/-/issues/5

**Comment by wdconinc** [comment]
Fixing that issue required having a way to refer to ip6 without using a symlink. You see, it's all related :-)

**Comment by c-dilks** [comment]
I think this is good idea. Would it have any impact on the typical workflow of changing something in `compact/some_detector.xml`, and then calling `ddsim` (i.e., without running `cmake`)? I suppose if you set `$DETECTOR_PATH` to the directory that has your `compact/some_detector.xml`, then it would be fine.

**Comment by wdconinc** [comment]
Yes, I'd suggest that workflow would be easiest resolved by setting DETECTOR_PATH to a custom location.
