### ISSUE TITLE
HCal forward insert - increase number of W/Sc layers to 10

### ISSUE THREAD

**Issue by rymilton** [eic/epic#546]
**Is your feature request related to a problem? Please describe.**
The current implementation of the Hcal insert has 4 layers of W/Sc, similar to the LFHCAL. The actual design should have 10 layers of W/Sc.

**Describe the solution you'd like**
Increase the number of W/Sc layers to 10 and decrease the number of Steel/Sc layers from 60 to 54 (remove 6 layers of steel, add 6 layers of tungsten).

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Chao1009** [comment]
Closes with #547
