### ISSUE TITLE
dRICH z-position is wrong

### ISSUE THREAD

**Issue by c-dilks** [eic/epic#56]
### Environment: (where does this bug occur, have you tried other environments)
`main` branch, likely introduced from https://github.com/eic/epic/pull/20

### Steps to reproduce: (give a step by step account of how to trigger the bug)
Evident in geoviewer and `dawn` artifacts

### Expected Result: (what do you expect when you execute the steps above)
```
DRICH_zmin                     =      195.000
DRICH_zmax                     =      315.000
````

### Actual Result: (what do you get when you execute the steps above)
```
DRICH_zmin                     =      208.000
DRICH_zmax                     =      328.000
```

**Comment by wdconinc** [comment]
@c-dilks I assume you're working on fixing this already :-) ?
