### ISSUE TITLE
Detector Parameters Update: Central TOF/Tracker

### ISSUE THREAD

**Issue by Chao1009** [eic/epic#564]
A series of smaller issues from #552 
`det`: new value from 2023/09/27 parameter table
`sim`: current simulation value as of 2023/10/11
`template_var`: from which we extract the sim value in compact files. `Empty` means we do not know.
`stat`: `Correct`, `Missing`, or `Mismatched`

Please implement the new detector parameters, and try to fill in the `template_var` for the `Missing` ones if you think it's important for future simulation/design comparison.

Here is the detailed report for this detector subsystem:
CENTRAL DETECTOR, Barrel Time of Flight/Tracker, : 
```
CENTRAL DETECTOR, Barrel Time of Flight/Tracker, : 
                           det    sim          template_var        stat
Length (cm)              289.0  286.5  {{BarrelTOF_length}}  Mismatched
Inner Radius (cm)         56.0   63.0    {{BarrelTOF_rmin}}  Mismatched
Outer Radius (cm)         63.0   66.0    {{BarrelTOF_rmax}}  Mismatched
Offset from Center (cm)   27.0    NaN                 Empty     Missing
Physical Start (cm)     -117.5    NaN                 Empty     Missing
Physical End (cm)        171.5    NaN                 Empty     Missing

CENTRAL DETECTOR, HD Time of Flight/Tracker, : 
                           det  sim template_var     stat
Length (cm)               15.0  NaN        Empty  Missing
Inner Radius (cm)          8.0  NaN        Empty  Missing
Outer Radius (cm)         60.0  NaN        Empty  Missing
Offset from Center (cm)  180.0  NaN        Empty  Missing
Physical Start (cm)      180.0  NaN        Empty  Missing
Physical End (cm)        195.0  NaN        Empty  Missing
```

**Comment by Chao1009** [comment]
Hi @yezhenyu2003, do you plan to update the detector parameters?

**Comment by yezhenyu2003** [comment]
Changes completed. The BTOF/FTOF fit within their envelopes defined in the geometry database
