### ISSUE TITLE
Errors/Typos in the 2023/09 Detector Parameter Table

### ISSUE THREAD

**Issue by Chao1009** [eic/epic#576]
The detector parameter tables have recently been updated, https://eic.jlab.org/Geometry/Detector/Detector-20230929162408.html, including in csv at https://eic.jlab.org/Geometry/Detector/local/D/DetectorParameterTable-20230927.csv.

This issue is to collect possible errors or typos in the latest parameters table.

#559 
`BackwardServiceGap_Length` increased from 10.0 cm to 124.0 cm.

**Comment by wdconinc** [comment]
Numerical precision.
![image](https://github.com/eic/epic/assets/4656391/263ea2c4-9222-43fe-8729-baa2b76b9ac7)

**Comment by Chao1009** [comment]
Geometry parameters are updated by fixing typos in the inner tracker section.
The latest one can be found at https://eic.jlab.org/Geometry/Detector/Detector-20231013155913.html

**Comment by Chao1009** [comment]
LD service gap length is fixed in the latest version https://eic.jlab.org/Geometry/Detector/Detector-20231020152234.html
124 cm -> 15 cm
