### ISSUE TITLE
Outer MPGD layer overlaps with other detectors

### ISSUE THREAD

**Issue by veprbl** [eic/epic#60]
### Environment: (where does this bug occur, have you tried other environments)
- main
- HEAD

### Steps to reproduce: (give a step by step account of how to trigger the bug)
Look at dump-constants job artifact (constants.toml), or
`npdet_info dump ${DETECTOR_PATH}/ecce.xml` should work

### Expected Result: (what do you expect when you execute the steps above)
According to https://eic.jlab.org/Geometry/Detector/Detector-20220624102507.html:
```
DIRC_rmax                      =       74.500
DIRC_rmin                      =       71.500 
OuterMPGDBarrel_rmin           =       75.500 (?)
OuterMPGDBarrelLayer_rmax      =       74.500 
OuterMPGDBarrelLayer_rmin      =       76.500 
EcalBarrel_rmin                =       79.500 
```

### Actual Result: (what do you get when you execute the steps above)
```
DIRC_rmax                      =       78.500 
DIRC_rmin                      =       71.500 
OuterMPGDBarrel_rmin           =       81.000
OuterMPGDBarrelLayer_rmax      =       82.000 
OuterMPGDBarrelLayer_rmin      =       80.000 
EcalBarrel_rmin                =       83.500 
```

**Comment by veprbl** [comment]
Given https://github.com/eic/epic/blob/ef6fb8db6d08614e355a19e19940aba44396acd4/compact/definitions.xml#L529
it seems like `BarrelExtraSpace_thickness` was increased recently in 1385810f907ebe74a03be13e10debd500e125191, cc @sly2j

**Comment by wdconinc** [comment]
The values in the detector menagerie should be considered with care. How is the radius of staves defined? Inscribed or circumscribed circle?

**Comment by sly2j** [comment]
Feel free to set the correct values in ‘definitions.xml’ starting with the DIRC radius outward. Shouldn’t interfere with anything. I just made the tracker fit but nothing is validated against the menagerie right now.

**Comment by veprbl** [comment]
Reducing the `BarrelExtraSpace_thickness` fudge constant causes an overlap with TOF:
```
 = Overlap ov00001: world_volume/InnerMPGDSubAssembly_7/InnerMPGDBarrel_0/layer1_0 overlapping world_volume/BarrelTOF_13/layer1_0 ovlp=1.1
```

**Comment by sly2j** [comment]
There should not be a TOF right now, it’s not implemented right. If you rebase off main and regenerate XML the TOF should be disabled for now.

**Comment by mposik1983** [comment]
The outer barrel MPGD geometry will need to be updated. This layer is now seen as a planar detector with the same dimensions as the DIRC bars. These MPGD "bars" will then sit just above the DIRC bars in ~2cm available space inside the DIRC support. I attached an image from one of the GD/I presentations below. The full presentation is here: https://indico.bnl.gov/event/15892/

![Screen Shot 2022-08-22 at 9 53 59 AM](https://user-images.githubusercontent.com/2228075/185938128-784bf754-97fb-4813-8555-880bd5090a21.png)
.
