### ISSUE TITLE
Barrel HCal should implement tiles as separate valid gdml files instead of embedding gdml sections

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#614]
**Is your feature request related to a problem? Please describe.**
The xml file for the Barrel HCal currently embeds gdml sections instead of including them as valid self-contained gdml files. This increases the size of the xml file.

**Describe the solution you'd like**
Since we already include external gdml files for the steel radiator(s), we can apply the same approach to external gdml files for the tiles. These are small enough that tracking them in the main geometry repository makes sense (at this point, until more detail needs to be added or so). This would factorize the gdml and xml components more clearly and cleanly.

**Describe alternatives you've considered**
- We can keep the gdml sections inside the xml as we currently have it. This keeps the xml large and somewhat unwieldy. It also prevents us from ensuring that we don't start deviating from 'proper' gdml over time. It requires us to maintain the code to read vertices and facets.
- We can store the small gdml files in the epic-data repository. I have nothing specifically against this, but we wanted to keep epic-data for large objects that cannot be stored in the epic geometry repository efficiently. That does not apply to the small tiles (until more detail needs to be added or so). The epic-data repository is currently not structured for a large number of objects and a bit of temporary solution.

**Comment by johnlajoie** [comment]
Completed in PR #588
