### ISSUE TITLE
Polystyrene differs from Geant4's G4_POLYSTYRENE

### ISSUE THREAD

**Issue by rymilton** [eic/epic#66]
**Is your feature request related to a problem? Please describe.**
The definition of Polystyrene in compact/materials.xml differs from G4_POLYSTYRENE in Geant4.

**Describe the solution you'd like**
Change the definition of Polystyrene to replicate G4_POLYSTYRENE -- density 1.06 g/cm^3, 50% C 50% H (Wikipedia says multiples of C8H8), mass fractions of 92.26% and 7.74% for C and H, respectively.
**Describe alternatives you've considered**
Maintain the current definition of Polystyrene.

**Additional context**
G4_POLYSTYRENE information from Geant4's material table:
![image](https://user-images.githubusercontent.com/87345122/185541473-09bb8c0f-bdd2-474a-8187-af0201e347fb.png)

**Comment by sly2j** [comment]
There are different types of polystyrene, the one that's in here is the one used for the imaging barrel Ecal. Are you sure you want the G4_POLYSTYRENE definition for the scintillator you are using? If so, we should probably use some more descriptive names (maybe based on the density).

**Comment by wdconinc** [comment]
Can we add `<comment>`s to material definitions? That would be a good place to link to an SDS or similar supplier documentation as a reference.

**Comment by rymilton** [comment]
Ah, I just assumed that the polystyrene definition was trying to replicate the G4_POLYSTYRENE definition but had an error. I'll inquire into which material specifically we want and implement it if needed. 

Since the imaging barrel Ecal uses this polystyrene definition, we should not change it. But I agree with Wouter that we should include comments about where the materials are coming from and what systems they are for.
