### ISSUE TITLE
Missing Support/Service material for MPGDs

### ISSUE THREAD

**Issue by mposik1983** [eic/epic#75]
**Is your feature request related to a problem? Please describe.**
The mpgd layers currently do not have support/service material implemented. 

**Describe the solution you'd like**
Proper materials used for support and services  should be implemented. These features include detector supports for the MPGD modules and approximate material for ASICs and cabling.

**Describe alternatives you've considered**
Some of this material has been incorporated by implementing an additional fudge factor layer whose thickness approximates some of the support/service average material.

These layers for the inner and outer barrel in mpgd_barrel.xml are shown below:

![Screen Shot 2022-08-24 at 8 02 08 PM](https://user-images.githubusercontent.com/2228075/186544797-bddc6e62-2f3e-4448-a947-8994e49e1903.png)

**Comment by wdconinc** [comment]
@sly2j What do you think of this proposal? (tutorial, ignore please)
