### ISSUE TITLE
Outer MPGD layer geometry change

### ISSUE THREAD

**Issue by mposik1983** [eic/epic#76]
**Is your feature request related to a problem? Please describe.**
The outer MPGD layer behind the DIRC needs to be changed from cylindrical geometry into rectangular geometry that mimics the geometry of the DIRC bars.

**Describe the solution you'd like**
Replace the cylindrical outer MPGD layer with rectangular geometry.

**Additional context**
This layer is integrated into the DIRC geometry and will sit in a 2cm space just above the DIRC bars

![185938128-784bf754-97fb-4813-8555-880bd5090a21](https://user-images.githubusercontent.com/2228075/186545566-5beebd18-1158-480e-8876-24173e338ecb.png)

**Comment by wdconinc** [comment]
@mposik1983

**Comment by yasirali12345** [comment]
@mposik1983 sorry just for tutorial
