### ISSUE TITLE
missing MPGD hits 

### ISSUE THREAD

**Issue by ShujieL** [eic/epic#774]
### Environment: (where does this bug occur, have you tried other environments)
I generated some 10 GeV pi+ events at theta between 70 to 110 degrees with epic 24.08.1, and noticed that more than 10% events has no hits on inner MPGD.

I also checked a simulation campaign file and saw similar behaviors
EPIC/RECO/24.07.0/epic_craterlake/SINGLE/pi+/10GeV/45to135deg/pi+_10GeV_45to135deg.0000.eicrecon.tree.edm4eic.root'

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. open one of the single event sample as mentioned about, and extract the branch "MPGDBarrelRawHits" with uproot
2. check the number of events with at least one MPGDBarrel hits, e.g. len(br.entry.unique()), and compare the returned number to the total mc event number. 

### Expected Result: (what do you expect when you execute the steps above)
At 10 GeV and central angle, almost every single pi+ particle should trigger inner MPGD.

### Actual Result: (what do you get when you execute the steps above)
Less than 90% events have inner MPGD hits. This number is even lower for outer MPGD

**Comment by wdconinc** [comment]
@ShujieL Can you post some more diagnostics here since you already started looking into it?

**Comment by ShujieL** [comment]
@wdconinc With my 20k 10GeV pi+ sample at 70<theta<110 degrees, I got the following number of events with at least one hit at given radius range. The events missed MPGD seems to have no preference in theta and phi. 
----------------------------------------------------
Hit collection name  / rmin / rmax [mm] / # of events
SiBarrelVertexRecHits 30 42 20000
SiBarrelVertexRecHits 46 60 20000
SiBarrelVertexRecHits 115 130 20000
SiBarrelTrackerRecHits 265 280 20000
SiBarrelTrackerRecHits 415 450 20000
MPGDBarrelRecHits 540 600 16353
TOFBarrelHits 610 650 20000
OuterMPGDBarrelRecHits 700 750 13875

**Comment by wdconinc** [comment]
Can you rerun one specific event with the track reconstruction in debug log level and analyze whether the hit even gets turned into a measurement? We know that for slanted tracks through the 3mm thick MPGD layers there is a non-negligible chance that there is a geant4 step that ends in the middle of the gas volume. That leads to two tracker hits then and each is going to be a bit displaced from the actual location of the center plane crossing. Can you rule that out based on debug output in the tracker to measurement converter?

**Comment by ShujieL** [comment]
> Can you rerun one specific event with the track reconstruction in debug log level and analyze whether the hit even gets turned into a measurement? We know that for slanted tracks through the 3mm thick MPGD layers there is a non-negligible chance that there is a geant4 step that ends in the middle of the gas volume. That leads to two tracker hits then and each is going to be a bit displaced from the actual location of the center plane crossing. Can you rule that out based on debug output in the tracker to measurement converter?

those numbers are from RecHits which are converted from sim hits after digitization, before the tracker measurement conversion. Also, MPGDBarrelRawHits and MPGDBarrelRecHits have the same number of entries. So the hits are very likely missing in sim hits (geant4).

**Comment by wdconinc** [comment]
Interesting. Please post more as you find out more.

**Comment by ShujieL** [comment]
> Interesting. Please post more as you find out more.
I will check the impact of missing MPGD hits in tracking. Meanwhile, I'd suggest 
1. @mposik1983 can probably check if there are acceptance gaps on MPGD with track projection. 
2. @rahmans1 @Chao1009 does this have anything to do with some threshold in Geant4 ?

**Comment by mposik1983** [comment]
@ShujieL Thanks for already starting to look into this. I can look into the acceptance a bit more and I will also bring this up during today's MPGD meeting. One thing to keep in mind is that we know there are acceptance gaps in the outer MPGD barrel by design (follows DIRC bar geometry), so having less Sim hits in the outer MPGD barrel compared to the inner MPGD barrel should be expected.

**Comment by ShujieL** [comment]
It seems that the hits are missing from the sim hits to raw hits transition, i.e. digitization. See https://indico.bnl.gov/event/24735/contributions/96326/attachments/57062/97925/missing%20hits.pdf

**Comment by wdconinc** [comment]
Because the [SiliconTrackerDigi](https://github.com/eic/EICrecon/blob/main/src/algorithms/digi/SiliconTrackerDigi.cc) is used for the MPGDs, the only reasons why sim hits may not turn into sim hits are:
- they are below energy threshold (https://github.com/eic/EICrecon/blob/0e1566c91b04605618c4571e72c3cfba18b2cb11/src/algorithms/digi/SiliconTrackerDigi.cc#L62-L64),
- they are within the same 'pixel' that has already been hit (https://github.com/eic/EICrecon/blob/0e1566c91b04605618c4571e72c3cfba18b2cb11/src/algorithms/digi/SiliconTrackerDigi.cc#L75-L85; keep earliest hit).

**Comment by wdconinc** [comment]
With a threshold of 0.25 keV, that is the main reason for cutting MPGD hits here. Below is a  plot of the energy deposition for simulated hits, in x-axis units of GeV, so keV if you ignore the 10^-6. A cut of 0.25 keV cuts a sizeable fraction of these events. @mposik1983 Are these thresholds correct?

![image](https://github.com/user-attachments/assets/ae917faf-d3da-4bb9-9aeb-82b87915cbbf)

**Comment by mposik1983** [comment]
@wdconinc for now the threshold values should stay as they are. From the discussion at the tracking meeting, there should be some follow up next week about a new threshold estimate

**Comment by wdconinc** [comment]
Yeah, I didn't know you were going to present on this exact issue today :-)

**Comment by ShujieL** [comment]
I will close this thread as the MPGD threshold was updated. The remained issue with CKF handling the last hit will be tracked here https://github.com/eic/EICrecon/issues/1659
