### ISSUE TITLE
Add the 'correct' magnetic field

### ISSUE THREAD

**Issue by wdconinc** [eic/epic#79]
**Is your feature request related to a problem? Please describe.**
Currently, our simulations [read in the 1.5 T fieldmap from sPhenix.2d.dat](https://github.com/eic/epic/blob/3786ed695f63f92394f7ed853c4f2a83c6b1a976/compact/solenoid.xml#L329). This map is not rescaled to get the planned 1.7 T magnetic field.

**Describe the solution you'd like**
We should get input from GD/I and/or tracking on what the fieldmap configuration should be in the short term.

**Comment by Simple-Shyam** [comment]
@wdconinc

**Comment by yasirali12345** [comment]
@wdconinc Excellent job

**Comment by wdconinc** [comment]
We should use the field linked at https://wiki.bnl.gov/EPIC/index.php?title=Experimental_Solenoid, in particular https://wiki.bnl.gov/EPIC/images/3/3a/MARCO_v.6.4.1.1.2_1.7T_Magnetic_Field_Map_2022_10_05_rad_coords_cm_T.txt
