### ISSUE TITLE
Question/Issue with Status ID

### ISSUE THREAD

**Issue by Meatbally2** [eic/epic#817]
Hi,

I generated some eHe3 scattering events with BeAGLE, and used eicsmear and hepmc3ascii2root to convert the output to hepmc3 and hepmc3.tree.root formats. The status IDs from "particle.status" in the file looked like what I would expect for the hepmc3 status code for my sample. However, when I used the files (I tried both) as an input to run epic simulation, the IDs from "MCParticle.generatorStatus" in the simulation output were mostly 0. Below are the screenshots from the hepmc3.tree.root and the simulation output file:

**particle.status from hepmc3.tree.root**
<img width="1336" alt="Screen Shot 2024-12-10 at 19 40 43" src="https://github.com/user-attachments/assets/ea2cd5ca-aafe-477c-9616-74b8ca675b2b">

**MCParticle.generatorStatus  from edm4hep.root** (In this figure, I only analysed 10 events from the above file)
<img width="1544" alt="Screen Shot 2024-12-10 at 19 37 21" src="https://github.com/user-attachments/assets/0d2adec5-b8a6-4b4d-bb1b-66f4ec8068da">

I am not sure if this is a bug for running simulation on BeAGLE events, or if I am doing anything wrong. Any suggestions will be appreciated! Thank you so much!

### Environment: (where does this bug occur, have you tried other environments)
- Which branch (`main` for latest released): main (from the most up to date eic-shell)
- Which revision (`HEAD` for the most recent):
- Any specific OS or system where the issue occurs? I ran the analysis on BNL SDCC
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1.
2.

### Expected Result: (what do you expect when you execute the steps above)
I expect the MCParticle.generatorStatus to have similar result as particle.status in the hepmc3.tree.root.

**Comment by veprbl** [comment]
You need to filter out some entries by `MCParticles.simulatorStatus`'s bit 30
https://github.com/key4hep/EDM4hep/blob/main/edm4hep.yaml#L303 to remove Geant tracks
