### ISSUE TITLE
Run BeAGLE in EPIC

### ISSUE THREAD

**Issue by KongTu** [eic/epic#92]
**Is your feature request related to a problem? Please describe.**
BeAGLE by default cannot be run in dd4hep

**Describe the solution you'd like**
As long as it runs 

**Describe alternatives you've considered**
No idea. 

**Additional context**

**Comment by KongTu** [comment]
@KongTu  take a look

**Comment by veprbl** [comment]
No actionable items for this repository. Let's close.
